version: '3.8'
services:
  db:
    container_name: frustrated_panda
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=packettrackntracedb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local