name: Master CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Step 1 - Checkout main branch from Github
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3.5.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Step 3 - Let Github build with Maven project
      run: mvn -B package --file pom.xml
    
    - name: Step 4 - List the current directory
      run: ls -a

    - name: Step 5 - Target folder
      run: |
        cd target
        ls -a
    
    - name: Step 7 - Upload JAR
      #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
      uses: actions/upload-artifact@v2
      with:
        #Set artifact name
        name: artifact
        #From this path
        path: target/parcel-track-n-trace-1.0-SNAPSHOT.jar
