name: Master CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Step 1 - Checkout main branch from Github
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3.5.0
      with:
        java-version: 17

    - name: Step 3 - Let Github build with Maven project
      run: mvn -B package --file pom.xml
    
    - name: Step 4 - List the current directory
      run: ls -a

    - name: Step 5 - Target folder
      run: |
        cd target
        ls -a
