name: Master CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Step 1 - Checkout main branch from Github
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3.5.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Step 3 - Let Github build with Maven project
      env:
         db-url: ${{ secrets.POSTGRES_URL }}
         db-username: ${{ secrets.POSTGRES_USER }}
         db-password: ${{ secrets.POSTGRES_PASSWORD }}
      run: mvn clean install
      
    - name: Step 4 - List the current directory
      run: ls -a

    - name: Step 5 - Target folder
      run: |
        cd target
        ls -a
    
    - name: Step 7 - Upload JAR
      #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
      uses: actions/upload-artifact@v2
      with:
        #Set artifact name
        name: artifact
        #From this path
        path: target/parcel-track-n-trace-1.0-SNAPSHOT.jar
        
  deploy:
    #Depends on build's job
    needs: build
    name: CD
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        #Download the artifact which was uploaded in the build's job
        uses: actions/download-artifact@v2
        with:
          name: artifact
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: false
          application_name: bestesSWENTeam	
          environment_name: Bestesswenteam-env	
          version_label: ${{github.run_id}}
          region: us-east-1
          deployment_package: parcel-track-n-trace-1.0-SNAPSHOT.jar
